# Generated by Django 4.2.5 on 2024-03-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cover_letter", "0001_initial"),
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=500)),
                ("url", models.URLField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "No Applied"),
                            (1, "Applied"),
                            (2, "Interview"),
                            (3, "Rejected"),
                            (4, "Offer"),
                            (5, "Accepted"),
                            (6, "No call"),
                        ],
                        default=0,
                    ),
                ),
                ("date_applied", models.DateField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("raw_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job",
                        to="cover_letter.coverletter",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job",
                        to="cv.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["-deadline"],
            },
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("json_detail", models.TextField()),
                ("usage", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="job_details", to="job.job"
                    ),
                ),
            ],
        ),
    ]
