# Generated by Django 4.2.5 on 2024-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtemplate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
