# Generated by Django 4.2.5 on 2024-01-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("cv", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="profile_picture",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cv", to="users.profilepicture"
            ),
        ),
    ]
