# Generated by Django 4.2.5 on 2024-01-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("cv", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="about_me",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv",
                to="users.aboutme",
            ),
        ),
    ]
